export const programActions = {
  ADD: 'PROGRAM_ADD',
  UPDATE: 'PROGRAM_UPDATE',
  DELETE: 'PROGRAM_DELETE',
  SUPERSEDE: 'PROGRAM_SUPERSEDED',
  USED: 'PROGRAM_USED',
  CLONE: 'PROGRAM_CLONE',
  TMP_SET: 'PROGRAM_TMP_SET',
  TMP_COMMIT: 'PROGRAM_TMP_COMMIT',
  TMP_CLEAR: 'PROGRAM_TMP_CLEAR',
  ADD_STEP: 'PROGRAM_STEP_ADD',
  MODIFY_STEP: 'PROGRAM_STEP_MODIFY',
  DELETE_STEP: 'PROGRAM_STEP_DELETE'
}
