export const programActions = {
  ADD: 'PROGRAM_ADD',
  UPDATE: 'PROGRAM_UPDATE',
  DELETE: 'PROGRAM_DELETE',
  CLONE: 'PROGRAM_CLONE',
  ADD_STEP: 'PROGRAM_STEP_ADD',
  MODIFY_STEP: 'PROGRAM_STEP_MODIFY',
  DELETE_STEP: 'PROGRAM_STEP_DELETE'
}
