export const kilnActions = {
  ADD: 'KILN_ADD',
  UPDATE: 'KILN_UPDATE',
  CLONE: 'KILN_CLONE',
  DELETE: 'KILN_DELETE',
  TOGGLE_WORKING: 'KILN_TOGGLE_WORKING',
  INSTALL: 'KILN_INSTALL',
  RETIRE: 'KILN_RETIRE',
  RESURECT: 'KILN_RESURECT',
  TMP_SET: 'KILN_TMP_SET',
  TMP_UPDATE_FIELD: 'KILN_TMP_UPDATE_FIELD',
  TMP_UPDATE_CHECKBOX_FIELD: 'KILN_TMP_UPDATE_CHECKBOX_FIELD',
  TMP_UPDATE_FIELD_ERROR: 'KILN_TMP_UPDATE_FIELD_ERROR',
  TMP_COMMIT: 'KILN_TMP_COMMIT'
}
